apiVersion: v1
kind: Service
metadata:
  name: oap
  namespace: {{your_namespace}}
  labels:
    service: oap
spec:
  ports:
  - port: 12800
    name: rest
  - port: 11800
    name: grpc
  - port: 1234
    name: page
  selector:
    app: oap
