---
apiVersion: v1
kind: Service
metadata:
  name: mysql-test
  namespace: {{your_namespace}}
spec:
  type: NodePort
  selector:
    app: mysql-test
  ports:
  - name: mysql-test
    nodePort: {{Access_Port}}
    port: 3306
    targetPort: 3306
